# Generated by Django 4.2.3 on 2023-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Usertypename', models.CharField(max_length=50)),
            ],
        ),
    ]
