# Generated by Django 4.2.3 on 2023-08-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_role_usertypename'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('userpass', models.CharField(max_length=50)),
                ('useremail', models.EmailField(max_length=254)),
                ('userphone', models.IntegerField()),
                ('u_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('inactie', 'inactive')], max_length=50)),
                ('urole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.role')),
            ],
        ),
    ]
