# Generated by Django 4.2.3 on 2023-08-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankdetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bankname', models.CharField(max_length=50)),
                ('acnumbr', models.CharField(max_length=20)),
                ('Endmonth', models.CharField(choices=[('jan', '1'), ('feb', '2'), ('march', '3'), ('apr', '4'), ('may', '5'), ('jun', '6'), ('jul', '7'), ('aug', '8'), ('sep', '9'), ('oct', '10'), ('nov', '11'), ('dec', '12')], max_length=10)),
                ('endyear', models.CharField(choices=[('2020', '20'), ('2021', '21'), ('2022', '22'), ('2023', '23'), ('2024', '24'), ('2025', '25'), ('2026', '26'), ('2027', '27'), ('2028', '28'), ('2029', '29'), ('2030', '30')], max_length=20)),
                ('buserdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.userdetail')),
            ],
        ),
    ]
