# Generated by Django 4.2.3 on 2023-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_bankdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='Endmonth',
            field=models.CharField(choices=[('jan', 'jan'), ('feb', 'feb'), ('march', 'march'), ('apr', 'apr'), ('may', 'may'), ('jun', 'jun'), ('jul', 'jul'), ('aug', 'aug'), ('sep', 'sep'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='endyear',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=20),
        ),
    ]
